apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-10-21T10:28:19Z"
  labels:
    run: httpd
  name: httpd-nodeport
  namespace: default
  resourceVersion: "170176"
  uid: 03aca0a7-ce73-440e-9649-91ed1385ce1c
spec:
  clusterIP: 10.97.250.8
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: httpd
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
