apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-10-20T17:42:47Z"
  labels:
    run: httpd
  name: httpd-nodeport
  namespace: default
  resourceVersion: "159269"
  uid: 20ab5519-81bb-4125-ae21-18d106ded09c
spec:
  clusterIP: 10.98.75.60
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: httpd
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
