apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: equivalent/health_check_nginx
    name: nginx
    resources: {}
    livenessProbe:
      httpGet:
        path: /health-check
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
