apiVersion: v1
kind: Pod
metadata:
  name: wordpress
spec:
  containers:
  - image: wordpress
    name: wordpress
    resources: {}
    readinessProbe:
       exec:
        command:
        - cat
        - readme.html
       initialDelaySeconds: 15
       periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
