apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  initContainers:
    - image: busybox
      name: initial-app
      command: ["sh", "-c", "echo 'Some things need to be initialized before the main container starts';", "sleep 20"]
  containers:
  - image: nginx
    name: main-app
