apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - image: busybox
    name: container1
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
  - image: busybox
    name: container2
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
