apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: wordpress
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: wordpress
  template:
    metadata:
      labels:
        tier: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress

